/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Thin Node.js wrapper over decide-core.
 *
 * Holds registered questions and one trainable engine per question.
 * `train` / `calibrate` / `metrics` were added in M1/M2; the original
 * `defineQuestion` / `ask` / `questions` API is unchanged.
 */
export declare class DecideEngine {
  /**
   * Create an engine. Before M1 training lands on a question, `ask`
   * returns the M0 stub decision: fixed `mock_output` at `mock_confidence`.
   * Pass e.g. `new DecideEngine('{"route":"billing"}', 0.94)`.
   */
  constructor(mockOutputJson?: string | undefined | null, mockConfidence?: number | undefined | null)
  /**
   * Register a question. `policy_json` is optional; when omitted the
   * default policy (act >= 0.9, review in [0.6, 0.9), escalate below 0.6) is used.
   * Expected shape: `{"act_above": 0.9, "review_low": 0.6, "review_high": 0.9}`.
   */
  defineQuestion(name: string, inputSchemaJson: string, outputSchemaJson: string, policyJson?: string | undefined | null): void
  /**
   * Train a question's engine. `examples_json` is
   * `[{"input": <string|object>, "label": "..."}]`; object inputs have
   * their string values concatenated, same as `ask`.
   */
  train(questionName: string, examplesJson: string): void
  /**
   * Fit temperature scaling on held-out validation examples (same shape
   * as `train`). Reduces overconfidence; see `metrics`.
   */
  calibrate(questionName: string, validationJson: string): void
  /**
   * Calibration/training status as JSON:
   * `{"trained":true,"classes":[...],"temperature":1.0,
   *   "ece_before":0.12,"ece_after":0.04}` (`ece_after` is null until calibrated).
   */
  metrics(questionName: string): string
  /**
   * Ask a registered question. Returns the decision as a JSON string:
   * `{"output": {"label": "..."}, "confidence": 0.94, "action": "act"}`.
   * Uses the trained engine when the question has been trained, otherwise
   * the M0 mock stub from the constructor.
   */
  ask(questionName: string, inputJson: string): string
  /** List registered question names. */
  questions(): Array<string>
}
