"""Bounded lookahead over JumpPolicy's provably-safe candidate set.

The safety proof in policies.py is untouched: candidates are generated by
the EXACT same rules (the cycle step is always a candidate; forward jumps
only when z >= L, never over the apple's cycle cell, defensively checked).
Only the *pick* changes: instead of the greedy 1-step distance to the
apple, we simulate candidate sequences a few plies deep with a lightweight
forward model and take the first move of the best-scoring sequence.

Leaf scoring: (apples eaten in sim, -moves used if eaten, -distance).
Distance is BFS (like the greedy baseline) or Manhattan (cheap). With
respawn=True the sim also models the apple respawn (far-biased, like the
game) using a clone of the game's RNG, so branches can eat more than one
apple inside the search.
"""
import random
from collections import deque

try:
    from .snakelib import DELTA, bfs_distances, bfs_first_step, cycle_index
except ImportError:  # script-dir fallback
    from snakelib import DELTA, bfs_distances, bfs_first_step, cycle_index

_INF = 10 ** 9


class LookaheadPolicy:
    def __init__(self, depth=3, leaf="bfs", respawn=False):
        if leaf not in ("bfs", "manhattan", "progress", "bfs1", "hybrid"):
            raise ValueError(
                "leaf must be 'bfs', 'manhattan', 'progress', 'bfs1' or 'hybrid'")
        self.depth = depth
        self.leaf = leaf
        self.respawn = respawn
        self.phase_at = 64  # hybrid: cycle-distance threshold pursue vs race
        self.name = ("look-d%d-%s%s"
                     % (depth, leaf, "-respawn" if respawn else ""))
        self.jumps_taken = 0  # diagnostics, like JumpPolicy
        self.guard_trips = 0  # diagnostics: proof asserts 0
        self.nodes_expanded = 0  # diagnostics: search effort per game

    # -- setup ---------------------------------------------------------
    def reset(self, game):
        idx, path = cycle_index(game.w, game.h)
        self._idx = idx
        self._path = path
        self._n = len(path)
        self._zero = path[0]
        self._w, self._h = game.w, game.h
        self._move_of = {(dx, dy): m for m, (dx, dy) in DELTA.items()}
        self._z = 0 if tuple(game.snake[0]) == self._zero else _INF
        # Obstacle support (gavel demo extension; empty on upstream boards).
        self._obs = set(map(tuple, getattr(game, "obstacles", None) or ()))
        self.jumps_taken = 0
        self.guard_trips = 0
        self.nodes_expanded = 0

    def correct_z(self, executed_cell, z_before):
        """Re-sync the wraparound guard after the caller overrode a proposal."""
        self._z = 0 if tuple(executed_cell) == self._zero else z_before + 1

    # -- candidate generation: IDENTICAL rules to JumpPolicy ------------
    def _candidates(self, body, apple, z):
        head = body[0]
        i = self._idx[head]
        hx, hy = head
        length = len(body)
        body_set = set(body)
        tail = body[-1]
        # Cycle step first: always a legal move (proof), the safety backbone.
        cands = [self._path[(i + 1) % self._n]]
        k_apple = self._idx[apple]
        if z >= length:
            for dx, dy in DELTA.values():
                c = (hx + dx, hy + dy)
                if c in self._obs:
                    continue  # pillar: never a jump target
                j = self._idx.get(c)
                if j is None or j <= i + 1:
                    continue
                if i < k_apple < j:
                    continue  # would overshoot the apple
                # Proof says c is free; checked anyway.
                if c in body_set and not (c == tail and c != apple):
                    self.guard_trips += 1
                    continue
                cands.append(c)
        return cands

    # -- lightweight forward model (mirrors Game.step) -----------------
    def _sim_step(self, body, apple, z, c, rng):
        eat = (c == apple)
        nb = [c] + (body if eat else body[:-1])  # grow on eat; tail vacates
        nz = 0 if c == self._zero else z + 1
        # cycle-index units advanced (wraparound counts as +1)
        prog = (self._idx[c] - self._idx[body[0]]) % self._n
        na, nrng = apple, rng
        if eat and self.respawn:
            na, nrng = self._sim_spawn(nb, rng)
        return nb, na, nz, nrng, eat, prog

    def _sim_spawn(self, body, rng):
        """Mirror of Game._spawn: far-biased free cell, reachable from head."""
        w, h = self._w, self._h
        occ = set(body) | set(self._obs)
        head = body[0]
        seen = {head}
        queue = deque([head])
        while queue:
            x, y = queue.popleft()
            for dx, dy in DELTA.values():
                c = (x + dx, y + dy)
                if (0 <= c[0] < w and 0 <= c[1] < h
                        and c not in occ and c not in seen):
                    seen.add(c)
                    queue.append(c)
        free = [(x, y) for x in range(w) for y in range(h)
                if (x, y) not in occ and (x, y) in seen] or \
               [(x, y) for x in range(w) for y in range(h)
                if (x, y) not in occ]
        if not free:
            return None, rng  # board full: game won
        hx, hy = head
        free.sort(key=lambda c: abs(c[0] - hx) + abs(c[1] - hy))
        far = free[len(free) // 2:] or free
        nrng = random.Random()  # independent clone per branch
        nrng.setstate(rng.getstate())
        return nrng.choice(far), nrng

    # -- leaf evaluation ------------------------------------------------
    def _leaf_key(self, body, apple, eaten, used, prog):
        if apple is None:
            return (eaten + 1, -used, _INF, 0)  # board clear: game won
        if eaten:
            return (eaten, -used, 0, 0)  # more apples, sooner, is better
        hx, hy = body[0]
        if self.leaf == "bfs":
            blocked = set(body) | set(self._obs)
            blocked.discard(body[0])   # the head: we measure distance TO it
            blocked.discard(body[-1])  # tail vacates on a non-growing step
            d = bfs_distances(apple, blocked, self._w, self._h).get(
                body[0], _INF)
            return (0, 0, -d, 0)
        d = abs(hx - apple[0]) + abs(hy - apple[1])
        if self.leaf == "manhattan":
            return (0, 0, -d, 0)
        if self.leaf == "progress":
            # maximize cycle-index advance (race the lap when the
            # apple is behind); Manhattan distance as a cheap aim tiebreak.
            return (0, prog, -d, 0)
        # bfs1 / hybrid: one shared BFS from decide() time (blocked =
        # current body minus tail); the leaf head is never inside the
        # current body (proof), so the lookup always hits.
        d1 = self._bfs1.get(body[0], _INF)
        if self.leaf == "bfs1":
            return (0, 0, -d1, 0)
        # hybrid: BFS pursuit when the apple is close ahead in cycle
        # order, otherwise race the lap (max cycle progress).
        cdist = (self._k_apple - self._idx[body[0]]) % self._n
        if cdist < self.phase_at:
            return (0, 0, -d1, 0)
        # race: progress first, then aim.
        return (0, prog, -d1, 0)

    # -- exhaustive DFS --------------------------------------------------
    def _dfs(self, body, apple, z, depth, rng, eaten, used, prog):
        if apple is None or depth == 0 or (eaten and not self.respawn):
            return self._leaf_key(body, apple, eaten, used, prog)
        best = None
        for c in self._candidates(body, apple, z):
            self.nodes_expanded += 1
            nb, na, nz, nrng, ate, dp = self._sim_step(
                body, apple, z, c, rng)
            key = self._dfs(nb, na, nz, depth - 1, nrng,
                             eaten + ate, used + 1, prog + dp)
            if best is None or key > best:
                best = key
        return best

    # -- decision ---------------------------------------------------------
    def decide(self, game):
        body = [tuple(c) for c in game.snake]
        apple = tuple(game.apple)
        cands = self._candidates(body, apple, self._z)
        cycle_next = cands[0]
        free = [c for c in cands if c not in self._obs]
        if not free:
            # Backbone severed and no jump: BFS detour around the pillar
            # (same escape as JumpPolicy); None only when truly trapped.
            via = bfs_first_step(body[0], apple,
                                 set(body) | set(self._obs),
                                 self._w, self._h, body[-1])
            target = via if via is not None else cycle_next
        elif len(free) == 1 or self.depth <= 0:
            target = free[0]  # no choice: skip the search (fast path)
        else:
            cands = free
            rng = None
            if self.respawn:
                rng = random.Random()
                rng.setstate(game.rng.getstate())
            if self.leaf in ("bfs1", "hybrid"):
                # One shared BFS at decide time (same blocking as the
                # greedy baseline); leaves look up into it.
                blocked0 = set(body) | set(self._obs)
                blocked0.discard(body[-1])
                self._bfs1 = bfs_distances(apple, blocked0,
                                           self._w, self._h)
                self._k_apple = self._idx[apple]
            # Shallow search: deeper plies were measured worse (the leaf
            # heuristic degrades with depth), so depth stays small.
            depth = self.depth
            best_key, target = None, cycle_next
            for c in cands:
                nb, na, nz, nrng, ate, dp = self._sim_step(
                    body, apple, self._z, c, rng)
                key = self._dfs(nb, na, nz, depth - 1, nrng, ate, 1, dp)
                # Tiebreak: prefer the further-along-cycle first move,
                # mirroring the greedy policy's preference for jumps.
                tkey = (key, self._idx[c])
                if best_key is None or tkey > best_key:
                    best_key, target = tkey, c
        if target != cycle_next:
            self.jumps_taken += 1
        dx, dy = target[0] - body[0][0], target[1] - body[0][1]
        self._z = 0 if target == self._zero else self._z + 1
        return self._move_of[(dx, dy)]
