#!/usr/bin/env python3
"""Negation/advisory augmentation: 48 items DISJOINT from probe (36 train + 12 val).
Patterns mirror probe failure modes with fresh wording/lures/links.
Labels: phishing = lure+link traps (incl. negation-stuffed), legitimate = advisories/notifications.
Serialize exactly like phishing_repro.py."""
import json

AUG_TRAIN = [
    # --- legit advisories quoting lure tokens (the P1n/P2n killer) ---
    ("legitimate", "IT Alert: fake invoice emails",
     "A wave of fake invoice emails is going around. They claim you were billed twice and link to refund pages. We never bill twice and never send refund links. Forward them to security and delete them.",
     "Security Team", "security@company.com", "", ""),
    ("legitimate", "Do not trust password-reset emails",
     "Several staff received emails saying passwords expire this week with reset links. Those messages are not from IT. Our passwords never expire by email notice. Do not follow their reset links.",
     "IT Helpdesk", "helpdesk@company.com", "", ""),
    ("legitimate", "Parcel scam warning",
     "Scam texts claim your parcel is held and link to tracking pages asking fees. Our couriers never ask fees through links. Ignore delivery messages demanding payment and do not open them.",
     "Logistics Desk", "logistics@company.com", "", ""),
    ("legitimate", "No prize was issued",
     "No employee won any prize this quarter and no vouchers are owed. Messages telling you to claim winnings through a link are fraudulent. Report them instead of claiming anything.",
     "HR", "hr@company.com", "", ""),
    ("legitimate", "Shared-file policy reminder",
     "Finance never distributes reports through public file hosts. If a message from a free mailbox urges you to open a shared spreadsheet, that is not us. Delete it and do not download attachments.",
     "Finance", "finance@company.com", "", ""),
    ("legitimate", "Bank impersonation alert",
     "Your bank will never ask you to confirm your identity by clicking a link. Emails warning of locked cards with verification links are traps. Call the number on your card instead.",
     "IT Security", "security@company.com", "", ""),
    ("legitimate", "Travel refund fraud notice",
     "Fraudulent emails promise travel refunds for cancelled flights and link to claim forms. We issue refunds automatically with no links and no claim needed. Disregard such refund offers.",
     "Travel Desk", "travel@company.com", "", ""),
    ("legitimate", "Tax-season phishing warning",
     "Tax-season scams threaten penalties unless you verify records through a link today. The revenue office never works that way and never threatens by email. Do not verify anything through those links.",
     "Finance", "finance@company.com", "", ""),
    # --- negation-stuffed phishing (the P6b killer) ---
    ("phishing", "Do not delay: confirm now",
     "Do not wait and do not hesitate: unusual activity was found that is not normal. Confirm your identity today, not later.",
     "Verification Center", "verify@account-secure Services.com".replace(" ", ""),
     "Confirm identity", "http://confirm-id.ga/start"),
    ("phishing", "No reply needed, just sign in",
     "No reply is needed. Your mailbox is almost full, which cannot wait. Sign in through the link so nothing is lost.",
     "Mail Admin", "admin@mailbox-service.tk",
     "Increase quota", "http://mbox-quota.tk/up"),
    ("phishing", "Not spam: invoice attached",
     "This is not spam and not a scam. Your overdue invoice is attached. Pay now to avoid fees; do not ignore this notice.",
     "Billing Dept", "billing@invoices-due.ml",
     "Pay invoice", "http://pay-invoice.ml/due"),
    ("phishing", "Never miss this: document expiring",
     "Never ignore this notice. A confidential file shared with you is not available for long. Open it before it is gone.",
     "Doc Share", "shared@docs-delivery.ga",
     "Open file", "http://file-share.ga/doc"),
    ("phishing", "Not a drill: wallet review",
     "Not a drill. Your wallet shows a transfer you did not make. This cannot stay unresolved. Review the transfer now.",
     "Wallet Safety", "safety@wallet-check.tk",
     "Review transfer", "http://wallet-check.tk/review"),
    ("phishing", "Don't lose access: re-login",
     "Don't lose access to your account. Our records show a login that was not you. Re-login through the secure page at once.",
     "Access Team", "access@login-secure.ml",
     "Secure login", "http://login-secure.ml/in"),
    # --- legit notifications with benign links (the P5 killer) ---
    ("legitimate", "Build passed",
     "The nightly build passed with all tests green. Details on the dashboard.",
     "CI System", "ci@company.com", "dashboard", "https://ci.company.com/builds/4821"),
    ("legitimate", "Holiday calendar published",
     "The holiday calendar for next quarter is published. Check the dates and plan leave early.",
     "HR", "hr@company.com", "calendar", "https://intranet.company.com/holidays"),
    ("legitimate", "New VPN client available",
     "A new VPN client version is available on the software portal. Update at your convenience; nothing expires.",
     "IT Helpdesk", "helpdesk@company.com", "software portal", "https://it.company.com/software"),
    ("legitimate", "Cafeteria menu",
     "This week's cafeteria menu is out: soups, salads and grilled options daily.",
     "Office Manager", "office@company.com", "menu", "https://intranet.company.com/menu"),
    ("legitimate", "All-hands recording",
     "Missed the all-hands? The recording and slides are on the wiki for everyone.",
     "Comms", "comms@company.com", "recording", "https://wiki.company.com/all-hands"),
    ("legitimate", "Library books due",
     "Two library books are due back Friday. Renew online if you still need them.",
     "Library", "library@company.com", "renew", "https://library.company.com/renew"),
    # --- legit cancellations/negations (the P8n killer) ---
    ("legitimate", "Workshop postponed",
     "The Thursday workshop is postponed and will not meet this week. No preparation is needed.",
     "Training", "training@company.com", "", ""),
    ("legitimate", "Fire drill cancelled",
     "Today's fire drill is cancelled due to rain. Do not gather at the assembly point.",
     "Facilities", "facilities@company.com", "", ""),
    ("legitimate", "System maintenance called off",
     "Weekend maintenance is called off. Systems will stay online and no downtime is expected.",
     "IT Operations", "itops@company.com", "", ""),
    ("legitimate", "No survey this month",
     "There is no engagement survey this month. Ignore any survey links bearing our name; they are not ours.",
     "HR", "hr@company.com", "", ""),
    ("legitimate", "Parking changes revoked",
     "The announced parking changes are revoked and will not take effect. Keep using your current spot.",
     "Facilities", "facilities@company.com", "", ""),
    ("legitimate", "Deadline extended, nothing due",
     "The report deadline is extended by two weeks. Nothing is due Friday and no submission is required yet.",
     "PMO", "pmo@company.com", "", ""),
    # --- plain traps for balance ---
    ("phishing", "Claim your tax refund",
     "You are owed a tax refund of $312. Submit your bank details through the form to receive it this week.",
     "Tax Office", "refunds@tax-bureau.ml",
     "Submit details", "http://tax-bureau.ml/refund"),
    ("phishing", "CEO request: gift cards",
     "The CEO needs gift cards for a client event urgently. Buy them and send the codes back right away. Keep this quiet.",
     "CEO Office", "ceo@company-executive.com",
     "", ""),
    ("phishing", "Mailbox will be deleted",
     "Your mailbox will be deleted within 24 hours for inactivity. Keep it by confirming below.",
     "Mail Admin", "admin@mbox-keep.ga",
     "Keep mailbox", "http://mbox-keep.ga/confirm"),
    ("phishing", "Insurance document signature",
     "An insurance document needs your signature today. Review and sign through the portal link.",
     "Insurer", "docs@insure-sign.tk",
     "Sign document", "http://insure-sign.tk/s"),
    ("phishing", "Job offer: remote work",
     "You were selected for a remote data-entry role paying weekly. Pay a small training deposit to start earning.",
     "Recruiter", "jobs@hire-fast.ml",
     "Start now", "http://hire-fast.ml/start"),
    ("phishing", "Security update required",
     "A critical flaw affects your router. Install the attached updater file now or lose connectivity.",
     "Network Vendor", "support@router-patch.ga",
     "Download updater", "http://router-patch.ga/fix"),
]

AUG_VAL = [
    ("legitimate", "Overtime pay notice",
     "Overtime for last month is approved and will appear in the next payroll. No forms and no clicks are needed.",
     "Payroll", "payroll@company.com", "", ""),
    ("legitimate", "Beware fake charity drive",
     "Fake charity emails trade on recent events and link to donation pages. Our giving program never solicits by email links. Do not donate through those pages.",
     "Comms", "comms@company.com", "", ""),
    ("legitimate", "Interview schedule change",
     "Friday interviews move to the second floor. Candidates were told already; no action on your part.",
     "Hiring", "hiring@company.com", "", ""),
    ("legitimate", "Gym reopening",
     "The office gym reopens Monday with extended hours. Towels are provided again.",
     "Facilities", "facilities@company.com", "hours", "https://intranet.company.com/gym"),
    ("legitimate", "No flu shots on site",
     "There will be no on-site flu shots this year. Visit any pharmacy instead; nothing to book here.",
     "HR", "hr@company.com", "", ""),
    ("legitimate", "Wire instructions never change by email",
     "Vendor wire instructions never change through email. Calls demanding urgent payment updates with new account links are fraud. Confirm by a known phone number.",
     "Finance", "finance@company.com", "", ""),
    ("phishing", "Don't skip: benefits enrollment",
     "Don't skip benefits enrollment. Your current plan is not carried over. Enroll through the link or lose coverage.",
     "Benefits", "benefits@enroll-now.tk",
     "Enroll", "http://enroll-now.tk/benefits"),
    ("phishing", "Not delivered: customs fee",
     "Your parcel is not delivered. A small customs fee is not yet paid. Settle it through the page to release the parcel.",
     "Customs", "post@parcel-fee.ml",
     "Pay fee", "http://parcel-fee.ml/pay"),
    ("phishing", "Never share codes, except here",
     "Never share login codes with anyone, except on this verification page which needs yours now to stop an intruder.",
     "Account Safety", "safety@login-verify.ga",
     "Verify", "http://login-verify.ga/code"),
    ("phishing", " Scholarship awarded",
     "A scholarship was awarded to you. No application was needed. Send an issuance fee to receive the funds.",
     "Foundation", "awards@scholar-fund.ml",
     "Receive funds", "http://scholar-fund.ml/accept"),
    ("phishing", "Voicemail received, open attachment",
     "You have one voicemail message that cannot be played online. Open the attached player file to listen.",
     "Phone System", "voip@voice-msgs.tk",
     "", ""),
    ("phishing", "Cloud storage full, upgrade free",
     "Your cloud storage is full, which cannot be ignored. An upgrade is free today only through this link.",
     "Cloud Team", "storage@cloud-up.tk",
     "Upgrade", "http://cloud-up.tk/free"),
]


def serialize(label, subject, body, sender, frm, link_text, link_url):
    return {"input": (f"from: {frm} sender: {sender} subject: {subject} "
                      f"link_text: {link_text} link_url: {link_url} body: {body}"),
            "label": label}


if __name__ == "__main__":
    tr = [serialize(*a) for a in AUG_TRAIN]
    va = [serialize(*a) for a in AUG_VAL]
    json.dump(tr, open("D:/gavel/models/training_state/negation_aug_train.json", "w"))
    json.dump(va, open("D:/gavel/models/training_state/negation_aug_val.json", "w"))
    from collections import Counter
    print("train:", len(tr), Counter(x["label"] for x in tr), flush=True)
    print("val:", len(va), Counter(x["label"] for x in va), flush=True)
